spring.application.name=mas_spring

spring.datasource.url=jdbc:h2:file:./data/vetclinic
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=25
spring.mail.username=ac4399b6b3e179
spring.mail.password=8c57d3c2823ae8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true