spring.application.name=mas_spring

spring.datasource.url=jdbc:h2:file:./data/vetclinic
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

spring.config.import=optional:file:./application-secret.properties
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=25
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true